linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports

linters-settings:
  gocritic:
    settings:
      captLocal: 
        onlyMyFuncs: false
    enabled-tags:
      - performance
      - style
      - experimental
      - opinionated

run:
  skip-files:
    - "**/*_test.go"
    - "**/testdata/**"
    - "**/mocks/**"

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .* is not checked"