linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports

linters-settings:
  gocritic:
    settings:
      captLocal: 
        paramsOnly: false
    enabled-tags:
      - performance
      - style
      - experimental
      - opinionated

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .* is not checked"
  exclude-dirs:
    - testdata
    - mocks
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - gocyclo
        - funlen
        - gosec
        - gocognit
        - gomnd
        - lll
        - wsl
        - gomoddirectives
        - gocritic
        - gosec
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused